add release instructions for the firmware
bitcraze/crazyflie-release pull request #9
Opened 2022-03-24 12:59 UTC by knmcguire

2022-03-25 07:34 UTC, krichardsson requested changes
Looking good! Some minor comments bellow. 

One option would be to put this in a docs directory to make it compatible with the web. Not sure there is any value in publishing it on the web as this mainly is an instruction for Bitcraze.

2022-03-25 07:34 UTC, krichardsson commented on release.md
> +1. Go to the draft release and input the generate thed release notes by  `tb ghrn bitcraze/crazyflie-firmware 2022.03`
Typo

2022-03-25 07:34 UTC, krichardsson commented on release.md
> +   * select the 'release' flow. Press the dow narrow on 'run workflow'
typo

2022-03-25 07:34 UTC, krichardsson commented on release.md
> +1. Locally clone this repository (crazyflie-release)
I would suggest to remove this part. As we move the build functionality to github, I think we should stop using the toolbelt release functionality (and remove it at some point). Just build the release candidate (in crazyflie-release) and use that for testing.

2022-03-29 07:34 UTC, knmcguire commented
Thanks kristoffer! I moved it to a docs folder now as well. 

Also I updated the doc to not use the toolbelt locally but just to generate the zipfiles directly with actions. People can just download it from the draft if they need to test it first. 

I'll merge it so that I can remove the old instructions

2022-03-29 07:34 UTC, merged